### ISSUE TITLE
Workspace could not be created

### ISSUE THREAD

**Issue by deanone** [eclipse-opensmartclide/smartclide-ide-front-end#32]
Hey all,

I tried to create a new service today, and while the respective repo has been successfully created it seems that the workspace creation process fails.

You can check the attached screenshot.

![front-end-interface-bug-1](https://user-images.githubusercontent.com/5978626/203732387-60dd1e71-afeb-4a7c-9736-9b17165943b9.png)

@goncalorolo can you please check this?

Best,

Athanasios

**Comment by goncalorolo** [comment]
I have just tried creating a service and everything worked. Can you please test again and provide more details in case the problem persists?

**Comment by deanone** [comment]
@goncalorolo I just tried it with a new service and received the error in the following figure:

![bug-1](https://user-images.githubusercontent.com/5978626/203972491-a5bd722e-c8ff-4779-959b-0a8ae6d9b779.png)

**Comment by goncalorolo** [comment]
@deanone, this last issue happened because we were migrating the devfile templates to another repository in order to be able to reduce the number of repos in the organisation. [Release 1.10](https://github.com/eclipse-opensmartclide/smartclide-ide-front-end/releases/tag/1.10) has fixed it.
