### ISSUE TITLE
No default space in jBPM interface

### ISSUE THREAD

**Issue by deanone** [eclipse-opensmartclide/smartclide-ide-front-end#33]
Hey all,

I tried to play around with the integrated jBPM interface today.

However, in order to do that there should be a default space in jBPM. However, none exists right now and I did not find any option to create a new one. You can check here:

![front-end-interface-bug-2](https://user-images.githubusercontent.com/5978626/203734858-c7c320c7-1119-4762-98f3-e3acdd620779.png)

@nikosnikolaidis is this a jBPM configuration issue?

@goncalorolo @nikosnikolaidis can you please check this?

Best,

Athanasios

**Comment by nikosnikolaidis** [comment]
Dear @deanone
In order to create a new space in jbpm you should have the appropriate account rights, @philipreimer can solve this for you.

But if we want to have a default space for each user, I can check it out.

**Comment by deanone** [comment]
@nikosnikolaidis yes I think it is better to have a default space for each user. @philipreimer can you check this?

**Comment by deanone** [comment]
> @deanone @nikosnikolaidis
> 
> > In order to create a new space in jbpm you should have the appropriate account rights
> 
> At the moment that seems to be the jbpm "admin" role - see https://jbpm.dev.smartclide.eu/business-central/kie-wb.jsp#SecurityManagementPerspective?activeTab=RolesTab%7CSecurityManagementHomeScreen,SecurityExplorerScreen?activeTab=RolesTab
> 
> @deanone is now also a jbpm "admin" and should be able to create new spaces, at least for himself.
> 
> > I think it is better to have a default space for each user.
> 
> Not sure how to do that in jbpm. I don't think we should give the "admin" role to every user.
> 
> I am not even sure if we should assign users a dedicated role that allows to create spaces. I am not familiar enough with jbpm to be able to assess the impact that would have, if any user can just create an arbitrary number of spaces.
> 
> I am also not sure if it is possible to create spaces for another user, or if it is possible to "share" spaces with other users? Even with the admin role I don't seem to be able to see any other spaces than the ones I created myself. The spaces settings allow to add "contributors" to a space. But that is limited to individual users, and does not support user roles or groups, it seems. So that does not seem to be an option either.
> 
> Maybe @teohaik can help?

@philipreimer I agree in your points. I think someone with a better understanding of spaces management in jBPM should guide us here. In principle, I would like users to have **one** space in which all their workflows will live. Now, the best option would be for this space to be  created and configured by us. We should not go into a direction of granting elevated rights to the users. I have limited knowledge of the jBPM design and operation, so I am not sure if this can be easily done.

@nikosnikolaidis any thoughts?

**Comment by nikosnikolaidis** [comment]
I agree with both of you @philipreimer @deanone.
I think that it is possible to have one space per user by default. As I have seen it locally but I am not sure how to do it.
As for the "correct" way that jBPM works I only know that we should take advantage of the roles that each user should have.

**Comment by teohaik** [comment]
Hello,

let me add in your discussion that the "spaces" concept has been introduced
as a way for teams to co-work and collaborate on common projects. So, yes,
it is possible (actually preferable) for a team with many individuals to
work on a common space.

Regards

Theodore

------------------

**Comment by deanone** [comment]
Hello all,

I am experimenting with the integrated jBPM interface and have seen that (for now) there is a default space in which I can create projects. Maybe, this is a configuration that @philipreimer did. So, I close the issue for now. Maybe we can re-open it (or create a new one similar to this) in the future if its needed.
