### ISSUE TITLE
Che workspace loading stales after importing a project identified by the service discovery module

### ISSUE THREAD

**Issue by deanone** [eclipse-opensmartclide/smartclide-ide-front-end#39]
Hi all,

I am experimenting with the integrated jBPM interface of our platform the last couple of days. I can create new projects in it, design business processes, add REST components in the diagrams, provide keywords for their functionalities and call the service discovery module. Then, I get back appropriate results back and when I select one of the returned services/projects, I am correctly redirected to the views for creating a new service. There, some fields are already pre-filled which is cool. Then, when I create the service, its code is fetched and new project is created on my GitLab account.

The problem is that when I hit the button to open the project in the platform, i.e., to load the respective Che workspace, it stales. I mean it keeps being in a state loading something (with a spinner circling around).

This is similar to other issues (e.g. #16 ), and I do not know (yet) if it is a bug or a performance issue (or a bug that leads to a performance issue).

@goncalorolo it would be very helpful for me if you could check this today and tomorrow (i.e., before my TheiaCon presentation).

**Comment by goncalorolo** [comment]
@deanone, #16 is a Che performance issue and has actually nothing to do with this one. This issue happened because I forgot to add the "latest" tag to the Che-Theia image and, therefore, the workspace starting process could not fetch it.

It should be fixed now, please test.

**Comment by deanone** [comment]
@goncalorolo I just tested it by fetching the code of a new discovered service and after 10 minutes the workspace still seems to be loading. I am testing on Firefox. Maybe deleting the cache or something can resolve this?

**Comment by goncalorolo** [comment]
I tested in Chrome and it took no more than 3min. You can try deleting cache and maybe even going to the Che dashboard and get rid of old workspaces that may be there hindering the process.

**Comment by deanone** [comment]
@goncalorolo it works fine. I have tested through the creation of 3 new services. Thanks a lot for working on this.

I am closing the issue.
