### ISSUE TITLE
Service creation - Cannot go to next step after Service Details

### ISSUE THREAD

**Issue by vagstef** [eclipse-opensmartclide/smartclide-ide-front-end#52]
After filling all required fields for the service creation the following error appears. note that it was possible to select the gitlab repository, also the Personal Access Token (PAT) was filled also before the creation attempt.

![bug1](https://user-images.githubusercontent.com/877582/209941856-e3b8a47f-1c34-42ac-b579-5ddf0a797949.PNG)

**Comment by deanone** [comment]
@vagstef any updates on this? As @nikosnikolaidis mentioned, the service name should not include spaces. In addition, the only supported Git system for now is GitLab. Furthermore, please check if the PAT has been copy-pasted correctly (sometimes, when you are doing copy paste from somewhere else, some additional characters like spaces, tabs or newlines may be added at the end of the copy-pasted string).

**Comment by vagstef** [comment]
Thank you @nikosnikolaidis. @deanone Not yet, I will thy this again as I was on leave

**Comment by deanone** [comment]
> Thank you @nikosnikolaidis. @deanone Not yet, I will thy this again as I was on leave

thanks @vagstef . Please ping me here if you need any assistance.

**Comment by vagstef** [comment]
@deanone I've finally managed to create the service so you can close this ticket

**Comment by deanone** [comment]
Thanks @vagstef
