### ISSUE TITLE
hard-coded jbpm URL in Workflows.vue

### ISSUE THREAD

**Issue by philipreimer** [eclipse-opensmartclide/smartclide-ide-front-end#56]
`<iframe id="jbpm-iframe" src="https://jbpm.dev.smartclide.eu/business-central/kie-wb.jsp"/>`

The URL to jbpm needs to be configurable via environment variable so that smartclide can be deployed under a different domain.

**Comment by goncalorolo** [comment]
Solved by [this](https://github.com/eclipse-opensmartclide/smartclide-ide-front-end/commit/dc054800db4630c5ab1b4703db4280777006d067) commit.
